'use client';
import {Button} from "@/components/ui/button";
import {Download} from "lucide-react";

export default function DownloadSummaryButton(
    {title,
     summaryText,
     fileName,
     createdAt,
    }:{
        title:string;
        summaryText:string;
        fileName:string;
        createdAt:string;
    }
){
    const handleDownload = () => {
       const summaryContent =  `
# ${title}
## Generated Summary
## Generated on: ${new Date(createdAt).toLocaleDateString()}
       
${summaryText}
       
Original File: ${fileName}
Generated By Summafy 💫
       
       
       `;

       const blob = new Blob([summaryContent],{type:'text/plain'});
       const url = URL.createObjectURL(blob);
       const link = document.createElement('a');
       link.href = url;
       link.download = `Summary-${title
           .replace(/[^a-z0-9]/gi,'_')}.txt`;
       link.click();
        document.body.appendChild(link);
        link.click();
        setTimeout(() => {
            document.body.removeChild(link);
            URL.revokeObjectURL(url);
        }, 100);
    };
    return(
        <Button onClick={handleDownload} size={"sm"} className={"h-8 rounded-full px-3 bg-purple-200 text-purple-500 hover:bg-purple-50 border hover:border-purple-500 hover:scale-105 transition-all duration-300 ease-in-out"}>
            <Download className={"h-4 w-4 mr-1"}/>
            Download Summary
        </Button>
    )

}